CREATE DATABASE [KhairulMisfitTestDB]
GO

USE [KhairulMisfitTestDB]
GO

CREATE TABLE [dbo].[UserResult](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstNumber] [varchar](max) NOT NULL,
	[SecondNumber] [varchar](max) NOT NULL,
	[Sum] [varchar](max) NOT NULL,
	[DateOfCalculation] [datetime] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_UserResult] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


